// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRiNsO1CDJWM45VytECVTeLjXWRLKkjzw',
    appId: '1:357030757607:android:a790b3da7d58e0c1058e42',
    messagingSenderId: '357030757607',
    projectId: 'expensio-d9892',
    storageBucket: 'expensio-d9892.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaOoM1JJJ86yRJGa6iVpZ4NCCTUCK1emA',
    appId: '1:357030757607:ios:a9488c9d57bf0eee058e42',
    messagingSenderId: '357030757607',
    projectId: 'expensio-d9892',
    storageBucket: 'expensio-d9892.firebasestorage.app',
    androidClientId: '357030757607-tub9udofe3q282qfgs7gft8hq0r2vp6q.apps.googleusercontent.com',
    iosClientId: '357030757607-dftqr3s13gtl9gnli2lck0kuolls2or7.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensio',
  );
}
